### ISSUE TITLE
Please attach a license

### ISSUE THREAD

**Issue by marcelpetrick** [FraPochetti/KagglePlaygrounds#11]
Hello, 
I noticed your repo does not mention any license. Therefore you are the sole copyright holder. And everyone - including me - can have a nice look at your magnificent work, but not use it by forking.

Greetings, Marcel

**Comment by FraPochetti** [comment]
[Done](https://github.com/FraPochetti/KagglePlaygrounds/blob/master/LICENSE)
Thanks for flagging

**Comment by marcelpetrick** [comment]
Thanks for the quick completion! @FraPochetti
